# Generated by Django 4.2.6 on 2024-01-02 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_insta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='insta',
        ),
    ]
