# Generated by Django 4.2.6 on 2024-01-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_insta'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='insta',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
