# Generated by Django 4.2.6 on 2024-01-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_user_insta_remove_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='new_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('insta', models.CharField(max_length=30)),
            ],
        ),
    ]
