# Generated by Django 4.2.6 on 2024-01-02 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_new_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='new_user',
            new_name='prac',
        ),
    ]
